In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
# Load the environment
env = gym.make("FrozenLake-v1")

In [3]:
# get the size of the action and state to build q_table
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 10000
max_steps_per_episode = 100    # agent can take 100 stems per episode

learning_rate = 0.1
discount_rate = 0.99           # gamma

# make a balance between exploration and exploitation
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [5]:
rewards_all_episodes = [] # can track the score

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False  # keep track whether episode is finishing or not
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        
        # exploitation
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        # exploration
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action]*(1-learning_rate) + \
        learning_rate * (reward + discount_rate*np.max(q_table[new_state, :]))
                         
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
    
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.05500000000000004
2000 :  0.19300000000000014
3000 :  0.3810000000000003
4000 :  0.5740000000000004
5000 :  0.6300000000000004
6000 :  0.6450000000000005
7000 :  0.6470000000000005
8000 :  0.6750000000000005
9000 :  0.6800000000000005
10000 :  0.6990000000000005


********Q-table********

[[0.55244661 0.54966928 0.53951542 0.51939275]
 [0.37428853 0.25990216 0.36075004 0.53565635]
 [0.42466734 0.44113654 0.3719124  0.50387387]
 [0.36568111 0.25677441 0.2687044  0.47845601]
 [0.56672474 0.39057733 0.35026907 0.33818691]
 [0.         0.         0.         0.        ]
 [0.40220904 0.18653896 0.2231409  0.16303265]
 [0.         0.         0.         0.        ]
 [0.41231983 0.36979719 0.37968987 0.61278385]
 [0.53598112 0.62708134 0.34887721 0.41817101]
 [0.53478729 0.38463192 0.31865299 0.2253329 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.21627805 0.50942547 0.76054221 

In [6]:
# Watch Q-learning Agent Play Game with trained data
for episode in range(3):
    state = env.reset()
    done = False
    print("********EPISODE ", episode+1, "********\n\n\n\n")
    # sleep for one second to read the above message
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state

env.close()

****You fell through a hole!****
